name: Java CD with Maven

on:
  push:
    branches:
      - test

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Extract project version
        id: extract_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create staging directory
        run: mkdir staging

      - name: Move JAR to staging directory
        run: mv target/*.jar staging

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging/*.jar
          retention-days: 1

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.VERSION }}
          title: "${{ env.VERSION }}"
          prerelease: false
          files: staging/*.jar

      - name: Push to master
        if: github.ref == 'refs/heads/test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin 
          git checkout master 
          git reset --hard origin/test 
          git push origin master --force