name: Java CI without Maven or Gradle

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java Code
        run: javac -d out src/**/*.java

      - name: Run JUnit 5 Tests
        run: |
          # Download JUnit 5 jar files (replace with actual URLs and paths)
          wget -P lib https://path-to-junit-jupiter-api-5.8.1.jar
          wget -P lib https://path-to-junit-jupiter-engine-5.8.1.jar
          wget -P lib https://path-to-apiguardian-api-1.1.2.jar
          wget -P lib https://path-to-opentest4j-1.2.0.jar

          # Run tests
          java -cp "lib/*:out" org.junit.platform.console.ConsoleLauncher --scan-class-path

      - name: Push to main if build and tests pass
        if: github.ref == 'refs/heads/dev'
        run: |
          git config --global user.email "ojcroveda@gmail.com"
          git config --global user.name "jota-br"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git checkout main
          git merge dev
          git push origin main