name: Java CI with JUnit 5

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package
        working-directory: ./

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./

      - name: Push to main if build and tests pass
        if: github.ref == 'refs/heads/dev'
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git checkout main
          git merge dev
          git push origin main
        working-directory: ./
